package app.tvlink.ui.theme

import androidx.compose.ui.graphics.Color

// M3 tone 阶梯色板，seed = 品牌青 #0E7490(≈tone40)。
// 浅/深双套角色的对比度由 tone 间距(≥40)保证,运行步骤人工核对观感。

// ---- light ----
val mdLightPrimary = Color(0xFF0E7490)
val mdLightOnPrimary = Color(0xFFFFFFFF)
val mdLightPrimaryContainer = Color(0xFFC5EFF7)
val mdLightOnPrimaryContainer = Color(0xFF032936)
val mdLightSecondary = Color(0xFF3E6B77)
val mdLightOnSecondary = Color(0xFFFFFFFF)
val mdLightSecondaryContainer = Color(0xFFD2E8EE)
val mdLightOnSecondaryContainer = Color(0xFF0E252B)
val mdLightTertiary = Color(0xFF9C4FA0)
val mdLightOnTertiary = Color(0xFFFFFFFF)
val mdLightTertiaryContainer = Color(0xFFF6D8F8)
val mdLightOnTertiaryContainer = Color(0xFF331039)
val mdLightError = Color(0xFFBA1A1A)
val mdLightOnError = Color(0xFFFFFFFF)
val mdLightErrorContainer = Color(0xFFF9DEDC)
val mdLightOnErrorContainer = Color(0xFF410E0B)
val mdLightBackground = Color(0xFFF5FAFB)
val mdLightOnBackground = Color(0xFF171D1F)
val mdLightSurface = Color(0xFFF5FAFB)
val mdLightOnSurface = Color(0xFF171D1F)
val mdLightSurfaceVariant = Color(0xFFDBE4E7)
val mdLightOnSurfaceVariant = Color(0xFF3F484B)
val mdLightOutline = Color(0xFF6F797C)
val mdLightOutlineVariant = Color(0xFFBFC8CB)
val mdLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val mdLightSurfaceContainerLow = Color(0xFFEFF5F6)
val mdLightSurfaceContainer = Color(0xFFE9F0F1)
val mdLightSurfaceContainerHigh = Color(0xFFE3EAEB)
val mdLightSurfaceContainerHighest = Color(0xFFDDE4E6)
val mdLightInverseSurface = Color(0xFF2C3133)
val mdLightInverseOnSurface = Color(0xFFECF2F3)
val mdLightInversePrimary = Color(0xFF8ADCEF)

// ---- dark ----
val mdDarkPrimary = Color(0xFF8ADCEF)
val mdDarkOnPrimary = Color(0xFF032936)
val mdDarkPrimaryContainer = Color(0xFF0A5B73)
val mdDarkOnPrimaryContainer = Color(0xFFC5EFF7)
val mdDarkSecondary = Color(0xFF9CC9D4)
val mdDarkOnSecondary = Color(0xFF0E252B)
val mdDarkSecondaryContainer = Color(0xFF2A4A54)
val mdDarkOnSecondaryContainer = Color(0xFFD2E8EE)
val mdDarkTertiary = Color(0xFFE3AEE6)
val mdDarkOnTertiary = Color(0xFF4A2450)
val mdDarkTertiaryContainer = Color(0xFF653769)
val mdDarkOnTertiaryContainer = Color(0xFFF6D8F8)
val mdDarkError = Color(0xFFF2B8B5)
val mdDarkOnError = Color(0xFF601410)
val mdDarkErrorContainer = Color(0xFF8C1D18)
val mdDarkOnErrorContainer = Color(0xFFF9DEDC)
val mdDarkBackground = Color(0xFF0E1517)
val mdDarkOnBackground = Color(0xFFDEE4E6)
val mdDarkSurface = Color(0xFF0E1517)
val mdDarkOnSurface = Color(0xFFDEE4E6)
val mdDarkSurfaceVariant = Color(0xFF3F484B)
val mdDarkOnSurfaceVariant = Color(0xFFBFC8CB)
val mdDarkOutline = Color(0xFF899396)
val mdDarkOutlineVariant = Color(0xFF3F484B)
val mdDarkSurfaceContainerLowest = Color(0xFF090F11)
val mdDarkSurfaceContainerLow = Color(0xFF171D1F)
val mdDarkSurfaceContainer = Color(0xFF1B2123)
val mdDarkSurfaceContainerHigh = Color(0xFF25292B)
val mdDarkSurfaceContainerHighest = Color(0xFF303537)
val mdDarkInverseSurface = Color(0xFFDEE4E6)
val mdDarkInverseOnSurface = Color(0xFF2C3133)
val mdDarkInversePrimary = Color(0xFF0E7490)
